### PR TITLE
DM-37545: Modernize package a bit

### PR DESCRIPTION
**Pull request by timj**

### CODE REVIEW

**Comment by timj** [comment]
@ktlim  I did this PR because nominally ctrl_execute does depend on ctrl_orca but it seems like it only really depends on it in the sense of the runOrca command calling orca.py.

**Comment by ktlim** [comment]
We should not be using ctrl_orca at all; that code and the dependency will need to be removed from ctrl_execute.

**Comment by timj** [comment]
Okay. I will remove the orca code from ctrl_execute

**Comment by timj** [comment]
Closing for now without merge since this package is still legacy.

**Pull request closed without merging**
